// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/4/2025, 1:32:50 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/warma/Desktop/New folder/donpollo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/plugins/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/donpollo/composables/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/donpollo/utils/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/donpollo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/donpollo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;