// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2025, 7:18:46 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/warma/Desktop/New folder/astma/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/plugins/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/astma/composables/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/astma/utils/**/*.{js,ts,mjs}","C:/Users/warma/Desktop/New folder/astma/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/warma/Desktop/New folder/astma/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;